/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "OTPKerberos"
 * 	found in "modules/otp-preauth-21.asn1"
 */

#ifndef	_AnyURI_H_
#define	_AnyURI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AnyURI */
typedef UTF8String_t	 AnyURI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AnyURI;
asn_struct_free_f AnyURI_free;
asn_struct_print_f AnyURI_print;
asn_constr_check_f AnyURI_constraint;
ber_type_decoder_f AnyURI_decode_ber;
der_type_encoder_f AnyURI_encode_der;
xer_type_decoder_f AnyURI_decode_xer;
xer_type_encoder_f AnyURI_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AnyURI_H_ */
