/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "KerberosV5Spec2"
 * 	found in "modules/KerberosV5Spec2.asn1"
 */

#ifndef	_EncryptedData_H_
#define	_EncryptedData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Int32.h"
#include "UInt32.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EncryptedData */
typedef struct EncryptedData {
	Int32_t	 etype;
	UInt32_t	*kvno	/* OPTIONAL */;
	OCTET_STRING_t	 cipher;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncryptedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncryptedData;

#ifdef __cplusplus
}
#endif

#endif	/* _EncryptedData_H_ */
