/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "KerberosV5Spec2"
 * 	found in "modules/KerberosV5Spec2.asn1"
 */

#ifndef	_EncryptionKey_H_
#define	_EncryptionKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Int32.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EncryptionKey */
typedef struct EncryptionKey {
	Int32_t	 keytype;
	OCTET_STRING_t	 keyvalue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncryptionKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncryptionKey;

#ifdef __cplusplus
}
#endif

#endif	/* _EncryptionKey_H_ */
