/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "KerberosV5Spec2"
 * 	found in "modules/KerberosV5Spec2.asn1"
 */

#ifndef	_KerberosString_H_
#define	_KerberosString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GeneralString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* KerberosString */
typedef GeneralString_t	 KerberosString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KerberosString;
asn_struct_free_f KerberosString_free;
asn_struct_print_f KerberosString_print;
asn_constr_check_f KerberosString_constraint;
ber_type_decoder_f KerberosString_decode_ber;
der_type_encoder_f KerberosString_encode_der;
xer_type_decoder_f KerberosString_decode_xer;
xer_type_encoder_f KerberosString_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _KerberosString_H_ */
