/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "KerberosV5Spec2"
 * 	found in "modules/KerberosV5Spec2.asn1"
 */

#ifndef	_LastReq_H_
#define	_LastReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "Int32.h"
#include "KerberosTime.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LastReq */
typedef struct LastReq {
	A_SEQUENCE_OF(struct Member {
		Int32_t	 lr_type;
		KerberosTime_t	 lr_value;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LastReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LastReq;

#ifdef __cplusplus
}
#endif

#endif	/* _LastReq_H_ */
