/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "KerberosV5Spec2"
 * 	found in "modules/KerberosV5Spec2.asn1"
 */

#ifndef	_Microseconds_H_
#define	_Microseconds_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Microseconds */
typedef long	 Microseconds_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Microseconds;
asn_struct_free_f Microseconds_free;
asn_struct_print_f Microseconds_print;
asn_constr_check_f Microseconds_constraint;
ber_type_decoder_f Microseconds_decode_ber;
der_type_encoder_f Microseconds_encode_der;
xer_type_decoder_f Microseconds_decode_xer;
xer_type_encoder_f Microseconds_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Microseconds_H_ */
