/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "OTPKerberos"
 * 	found in "modules/otp-preauth-21.asn1"
 */

#include <asn_internal.h>

#include "OTP-TOKENINFO.h"

static int
memb_otp_challenge_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_supportedHashAlg_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_supportedHashAlg_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_supportedHashAlg_specs_9 = {
	sizeof(struct supportedHashAlg),
	offsetof(struct supportedHashAlg, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_supportedHashAlg_9 = {
	"supportedHashAlg",
	"supportedHashAlg",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_supportedHashAlg_tags_9,
	sizeof(asn_DEF_supportedHashAlg_tags_9)
		/sizeof(asn_DEF_supportedHashAlg_tags_9[0]) - 1, /* 1 */
	asn_DEF_supportedHashAlg_tags_9,	/* Same as above */
	sizeof(asn_DEF_supportedHashAlg_tags_9)
		/sizeof(asn_DEF_supportedHashAlg_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_supportedHashAlg_9,
	1,	/* Single element */
	&asn_SPC_supportedHashAlg_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_OTP_TOKENINFO_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OTP_TOKENINFO, flags),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OTPFlags,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"flags"
		},
	{ ATF_POINTER, 8, offsetof(struct OTP_TOKENINFO, otp_vendor),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-vendor"
		},
	{ ATF_POINTER, 7, offsetof(struct OTP_TOKENINFO, otp_challenge),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_otp_challenge_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-challenge"
		},
	{ ATF_POINTER, 6, offsetof(struct OTP_TOKENINFO, otp_length),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Int32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-length"
		},
	{ ATF_POINTER, 5, offsetof(struct OTP_TOKENINFO, otp_format),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OTPFormat,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-format"
		},
	{ ATF_POINTER, 4, offsetof(struct OTP_TOKENINFO, otp_tokenID),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-tokenID"
		},
	{ ATF_POINTER, 3, offsetof(struct OTP_TOKENINFO, otp_algID),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AnyURI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-algID"
		},
	{ ATF_POINTER, 2, offsetof(struct OTP_TOKENINFO, supportedHashAlg),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_supportedHashAlg_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"supportedHashAlg"
		},
	{ ATF_POINTER, 1, offsetof(struct OTP_TOKENINFO, iterationCount),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Int32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iterationCount"
		},
};
static ber_tlv_tag_t asn_DEF_OTP_TOKENINFO_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_OTP_TOKENINFO_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* flags at 31 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* otp-vendor at 32 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* otp-challenge at 33 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* otp-length at 35 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* otp-format at 36 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* otp-tokenID at 37 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* otp-algID at 38 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* supportedHashAlg at 40 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* iterationCount at 41 */
};
static asn_SEQUENCE_specifics_t asn_SPC_OTP_TOKENINFO_specs_1 = {
	sizeof(struct OTP_TOKENINFO),
	offsetof(struct OTP_TOKENINFO, _asn_ctx),
	asn_MAP_OTP_TOKENINFO_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	8,	/* Start extensions */
	10	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_OTP_TOKENINFO = {
	"OTP-TOKENINFO",
	"OTP-TOKENINFO",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_OTP_TOKENINFO_tags_1,
	sizeof(asn_DEF_OTP_TOKENINFO_tags_1)
		/sizeof(asn_DEF_OTP_TOKENINFO_tags_1[0]), /* 1 */
	asn_DEF_OTP_TOKENINFO_tags_1,	/* Same as above */
	sizeof(asn_DEF_OTP_TOKENINFO_tags_1)
		/sizeof(asn_DEF_OTP_TOKENINFO_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_OTP_TOKENINFO_1,
	9,	/* Elements count */
	&asn_SPC_OTP_TOKENINFO_specs_1	/* Additional specs */
};

