/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "OTPKerberos"
 * 	found in "modules/otp-preauth-21.asn1"
 */

#ifndef	_OTP_TOKENINFO_H_
#define	_OTP_TOKENINFO_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OTPFlags.h"
#include <UTF8String.h>
#include <OCTET_STRING.h>
#include "Int32.h"
#include "OTPFormat.h"
#include "AnyURI.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlgorithmIdentifier;

/* OTP-TOKENINFO */
typedef struct OTP_TOKENINFO {
	OTPFlags_t	 flags;
	UTF8String_t	*otp_vendor	/* OPTIONAL */;
	OCTET_STRING_t	*otp_challenge	/* OPTIONAL */;
	Int32_t	*otp_length	/* OPTIONAL */;
	OTPFormat_t	*otp_format	/* OPTIONAL */;
	OCTET_STRING_t	*otp_tokenID	/* OPTIONAL */;
	AnyURI_t	*otp_algID	/* OPTIONAL */;
	struct supportedHashAlg {
		A_SEQUENCE_OF(struct AlgorithmIdentifier) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *supportedHashAlg;
	Int32_t	*iterationCount	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OTP_TOKENINFO_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OTP_TOKENINFO;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlgorithmIdentifier.h"

#endif	/* _OTP_TOKENINFO_H_ */
