/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "OTPKerberos"
 * 	found in "modules/otp-preauth-21.asn1"
 */

#ifndef	_OTPFlags_H_
#define	_OTPFlags_H_


#include <asn_application.h>

/* Including external dependencies */
#include "KerberosFlags.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OTPFlags */
typedef KerberosFlags_t	 OTPFlags_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OTPFlags;
asn_struct_free_f OTPFlags_free;
asn_struct_print_f OTPFlags_print;
asn_constr_check_f OTPFlags_constraint;
ber_type_decoder_f OTPFlags_decode_ber;
der_type_encoder_f OTPFlags_encode_der;
xer_type_decoder_f OTPFlags_decode_xer;
xer_type_encoder_f OTPFlags_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OTPFlags_H_ */
