/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "OTPKerberos"
 * 	found in "modules/otp-preauth-21.asn1"
 */

#ifndef	_OTPFormat_H_
#define	_OTPFormat_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OTPFormat {
	OTPFormat_decimal	= 0,
	OTPFormat_hexadecimal	= 1,
	OTPFormat_alphanumeric	= 2,
	OTPFormat_binary	= 3,
	OTPFormat_base64	= 4
} e_OTPFormat;

/* OTPFormat */
typedef INTEGER_t	 OTPFormat_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OTPFormat;
asn_struct_free_f OTPFormat_free;
asn_struct_print_f OTPFormat_print;
asn_constr_check_f OTPFormat_constraint;
ber_type_decoder_f OTPFormat_decode_ber;
der_type_encoder_f OTPFormat_encode_der;
xer_type_decoder_f OTPFormat_decode_xer;
xer_type_encoder_f OTPFormat_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OTPFormat_H_ */
