/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "KerberosV5Spec2"
 * 	found in "modules/KerberosV5Spec2.asn1"
 */

#include <asn_internal.h>

#include "PA-ENC-TS-ENC.h"

static asn_TYPE_member_t asn_MBR_PA_ENC_TS_ENC_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PA_ENC_TS_ENC, patimestamp),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_KerberosTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"patimestamp"
		},
	{ ATF_POINTER, 1, offsetof(struct PA_ENC_TS_ENC, pausec),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Microseconds,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pausec"
		},
};
static ber_tlv_tag_t asn_DEF_PA_ENC_TS_ENC_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PA_ENC_TS_ENC_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* patimestamp at 33 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* pausec at 34 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PA_ENC_TS_ENC_specs_1 = {
	sizeof(struct PA_ENC_TS_ENC),
	offsetof(struct PA_ENC_TS_ENC, _asn_ctx),
	asn_MAP_PA_ENC_TS_ENC_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PA_ENC_TS_ENC = {
	"PA-ENC-TS-ENC",
	"PA-ENC-TS-ENC",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PA_ENC_TS_ENC_tags_1,
	sizeof(asn_DEF_PA_ENC_TS_ENC_tags_1)
		/sizeof(asn_DEF_PA_ENC_TS_ENC_tags_1[0]), /* 1 */
	asn_DEF_PA_ENC_TS_ENC_tags_1,	/* Same as above */
	sizeof(asn_DEF_PA_ENC_TS_ENC_tags_1)
		/sizeof(asn_DEF_PA_ENC_TS_ENC_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PA_ENC_TS_ENC_1,
	2,	/* Elements count */
	&asn_SPC_PA_ENC_TS_ENC_specs_1	/* Additional specs */
};

