/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "OTPKerberos"
 * 	found in "modules/otp-preauth-21.asn1"
 */

#ifndef	_PA_OTP_REQUEST_H_
#define	_PA_OTP_REQUEST_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OTPFlags.h"
#include <OCTET_STRING.h>
#include "EncryptedData.h"
#include "Int32.h"
#include <UTF8String.h>
#include "KerberosTime.h"
#include "OTPFormat.h"
#include "AnyURI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlgorithmIdentifier;

/* PA-OTP-REQUEST */
typedef struct PA_OTP_REQUEST {
	OTPFlags_t	 flags;
	OCTET_STRING_t	*nonce	/* OPTIONAL */;
	EncryptedData_t	 encData;
	struct AlgorithmIdentifier	*hashAlg	/* OPTIONAL */;
	Int32_t	*iterationCount	/* OPTIONAL */;
	OCTET_STRING_t	*otp_value	/* OPTIONAL */;
	UTF8String_t	*otp_pin	/* OPTIONAL */;
	OCTET_STRING_t	*otp_challenge	/* OPTIONAL */;
	KerberosTime_t	*otp_time	/* OPTIONAL */;
	OCTET_STRING_t	*otp_counter	/* OPTIONAL */;
	OTPFormat_t	*otp_format	/* OPTIONAL */;
	OCTET_STRING_t	*otp_tokenID	/* OPTIONAL */;
	AnyURI_t	*otp_algID	/* OPTIONAL */;
	UTF8String_t	*otp_vendor	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PA_OTP_REQUEST_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PA_OTP_REQUEST;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlgorithmIdentifier.h"

#endif	/* _PA_OTP_REQUEST_H_ */
