/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "OTPKerberos"
 * 	found in "modules/otp-preauth-21.asn1"
 */

#include <asn_internal.h>

#include "PA-OTP-CHALLENGE.h"

static int
memb_otp_tokenInfo_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_otp_tokenInfo_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_OTP_TOKENINFO,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_otp_tokenInfo_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_otp_tokenInfo_specs_4 = {
	sizeof(struct otp_tokenInfo),
	offsetof(struct otp_tokenInfo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_otp_tokenInfo_4 = {
	"otp-tokenInfo",
	"otp-tokenInfo",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_otp_tokenInfo_tags_4,
	sizeof(asn_DEF_otp_tokenInfo_tags_4)
		/sizeof(asn_DEF_otp_tokenInfo_tags_4[0]) - 1, /* 1 */
	asn_DEF_otp_tokenInfo_tags_4,	/* Same as above */
	sizeof(asn_DEF_otp_tokenInfo_tags_4)
		/sizeof(asn_DEF_otp_tokenInfo_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_otp_tokenInfo_4,
	1,	/* Single element */
	&asn_SPC_otp_tokenInfo_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PA_OTP_CHALLENGE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PA_OTP_CHALLENGE, nonce),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nonce"
		},
	{ ATF_POINTER, 1, offsetof(struct PA_OTP_CHALLENGE, otp_service),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-service"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PA_OTP_CHALLENGE, otp_tokenInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_otp_tokenInfo_4,
		memb_otp_tokenInfo_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-tokenInfo"
		},
	{ ATF_POINTER, 2, offsetof(struct PA_OTP_CHALLENGE, salt),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_KerberosString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"salt"
		},
	{ ATF_POINTER, 1, offsetof(struct PA_OTP_CHALLENGE, s2kparams),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"s2kparams"
		},
};
static ber_tlv_tag_t asn_DEF_PA_OTP_CHALLENGE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PA_OTP_CHALLENGE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nonce at 21 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* otp-service at 22 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* otp-tokenInfo at 24 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* salt at 25 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* s2kparams at 26 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PA_OTP_CHALLENGE_specs_1 = {
	sizeof(struct PA_OTP_CHALLENGE),
	offsetof(struct PA_OTP_CHALLENGE, _asn_ctx),
	asn_MAP_PA_OTP_CHALLENGE_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PA_OTP_CHALLENGE = {
	"PA-OTP-CHALLENGE",
	"PA-OTP-CHALLENGE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PA_OTP_CHALLENGE_tags_1,
	sizeof(asn_DEF_PA_OTP_CHALLENGE_tags_1)
		/sizeof(asn_DEF_PA_OTP_CHALLENGE_tags_1[0]), /* 1 */
	asn_DEF_PA_OTP_CHALLENGE_tags_1,	/* Same as above */
	sizeof(asn_DEF_PA_OTP_CHALLENGE_tags_1)
		/sizeof(asn_DEF_PA_OTP_CHALLENGE_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PA_OTP_CHALLENGE_1,
	5,	/* Elements count */
	&asn_SPC_PA_OTP_CHALLENGE_specs_1	/* Additional specs */
};

