/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "OTPKerberos"
 * 	found in "modules/otp-preauth-21.asn1"
 */

#ifndef	_PA_OTP_ENC_REQUEST_H_
#define	_PA_OTP_ENC_REQUEST_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PA-OTP-ENC-REQUEST */
typedef struct PA_OTP_ENC_REQUEST {
	OCTET_STRING_t	 nonce;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PA_OTP_ENC_REQUEST_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PA_OTP_ENC_REQUEST;

#ifdef __cplusplus
}
#endif

#endif	/* _PA_OTP_ENC_REQUEST_H_ */
