/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "OTPKerberos"
 * 	found in "modules/otp-preauth-21.asn1"
 */

#ifndef	_PA_OTP_CHALLENGE_H_
#define	_PA_OTP_CHALLENGE_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <UTF8String.h>
#include "KerberosString.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OTP_TOKENINFO;

/* PA-OTP-CHALLENGE */
typedef struct PA_OTP_CHALLENGE {
	OCTET_STRING_t	 nonce;
	UTF8String_t	*otp_service	/* OPTIONAL */;
	struct otp_tokenInfo {
		A_SEQUENCE_OF(struct OTP_TOKENINFO) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} otp_tokenInfo;
	KerberosString_t	*salt	/* OPTIONAL */;
	OCTET_STRING_t	*s2kparams	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PA_OTP_CHALLENGE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PA_OTP_CHALLENGE;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OTP-TOKENINFO.h"

#endif	/* _PA_OTP_CHALLENGE_H_ */
