/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "OTPKerberos"
 * 	found in "modules/otp-preauth-21.asn1"
 */

#include <asn_internal.h>

#include "PA-OTP-PIN-CHANGE.h"

static asn_TYPE_member_t asn_MBR_PA_OTP_PIN_CHANGE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PA_OTP_PIN_CHANGE, flags),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PinFlags,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"flags"
		},
	{ ATF_POINTER, 5, offsetof(struct PA_OTP_PIN_CHANGE, pin),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pin"
		},
	{ ATF_POINTER, 4, offsetof(struct PA_OTP_PIN_CHANGE, minLength),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"minLength"
		},
	{ ATF_POINTER, 3, offsetof(struct PA_OTP_PIN_CHANGE, maxLength),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"maxLength"
		},
	{ ATF_POINTER, 2, offsetof(struct PA_OTP_PIN_CHANGE, last_req),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LastReq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"last-req"
		},
	{ ATF_POINTER, 1, offsetof(struct PA_OTP_PIN_CHANGE, format),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OTPFormat,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"format"
		},
};
static ber_tlv_tag_t asn_DEF_PA_OTP_PIN_CHANGE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PA_OTP_PIN_CHANGE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* flags at 89 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pin at 90 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* minLength at 91 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* maxLength at 92 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* last-req at 93 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* format at 94 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PA_OTP_PIN_CHANGE_specs_1 = {
	sizeof(struct PA_OTP_PIN_CHANGE),
	offsetof(struct PA_OTP_PIN_CHANGE, _asn_ctx),
	asn_MAP_PA_OTP_PIN_CHANGE_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PA_OTP_PIN_CHANGE = {
	"PA-OTP-PIN-CHANGE",
	"PA-OTP-PIN-CHANGE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PA_OTP_PIN_CHANGE_tags_1,
	sizeof(asn_DEF_PA_OTP_PIN_CHANGE_tags_1)
		/sizeof(asn_DEF_PA_OTP_PIN_CHANGE_tags_1[0]), /* 1 */
	asn_DEF_PA_OTP_PIN_CHANGE_tags_1,	/* Same as above */
	sizeof(asn_DEF_PA_OTP_PIN_CHANGE_tags_1)
		/sizeof(asn_DEF_PA_OTP_PIN_CHANGE_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PA_OTP_PIN_CHANGE_1,
	6,	/* Elements count */
	&asn_SPC_PA_OTP_PIN_CHANGE_specs_1	/* Additional specs */
};

