/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "OTPKerberos"
 * 	found in "modules/otp-preauth-21.asn1"
 */

#include <asn_internal.h>

#include "PA-OTP-REQUEST.h"

static int
memb_otp_challenge_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_PA_OTP_REQUEST_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PA_OTP_REQUEST, flags),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OTPFlags,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"flags"
		},
	{ ATF_POINTER, 1, offsetof(struct PA_OTP_REQUEST, nonce),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nonce"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PA_OTP_REQUEST, encData),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EncryptedData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"encData"
		},
	{ ATF_POINTER, 11, offsetof(struct PA_OTP_REQUEST, hashAlg),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"hashAlg"
		},
	{ ATF_POINTER, 10, offsetof(struct PA_OTP_REQUEST, iterationCount),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Int32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iterationCount"
		},
	{ ATF_POINTER, 9, offsetof(struct PA_OTP_REQUEST, otp_value),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-value"
		},
	{ ATF_POINTER, 8, offsetof(struct PA_OTP_REQUEST, otp_pin),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-pin"
		},
	{ ATF_POINTER, 7, offsetof(struct PA_OTP_REQUEST, otp_challenge),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_otp_challenge_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-challenge"
		},
	{ ATF_POINTER, 6, offsetof(struct PA_OTP_REQUEST, otp_time),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_KerberosTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-time"
		},
	{ ATF_POINTER, 5, offsetof(struct PA_OTP_REQUEST, otp_counter),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-counter"
		},
	{ ATF_POINTER, 4, offsetof(struct PA_OTP_REQUEST, otp_format),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OTPFormat,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-format"
		},
	{ ATF_POINTER, 3, offsetof(struct PA_OTP_REQUEST, otp_tokenID),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-tokenID"
		},
	{ ATF_POINTER, 2, offsetof(struct PA_OTP_REQUEST, otp_algID),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AnyURI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-algID"
		},
	{ ATF_POINTER, 1, offsetof(struct PA_OTP_REQUEST, otp_vendor),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"otp-vendor"
		},
};
static ber_tlv_tag_t asn_DEF_PA_OTP_REQUEST_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PA_OTP_REQUEST_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* flags at 64 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* nonce at 65 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* encData at 66 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* hashAlg at 69 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* iterationCount at 70 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* otp-value at 71 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* otp-pin at 72 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* otp-challenge at 73 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* otp-time at 74 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* otp-counter at 75 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* otp-format at 76 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* otp-tokenID at 77 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* otp-algID at 78 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 } /* otp-vendor at 79 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PA_OTP_REQUEST_specs_1 = {
	sizeof(struct PA_OTP_REQUEST),
	offsetof(struct PA_OTP_REQUEST, _asn_ctx),
	asn_MAP_PA_OTP_REQUEST_tag2el_1,
	14,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	13,	/* Start extensions */
	15	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PA_OTP_REQUEST = {
	"PA-OTP-REQUEST",
	"PA-OTP-REQUEST",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PA_OTP_REQUEST_tags_1,
	sizeof(asn_DEF_PA_OTP_REQUEST_tags_1)
		/sizeof(asn_DEF_PA_OTP_REQUEST_tags_1[0]), /* 1 */
	asn_DEF_PA_OTP_REQUEST_tags_1,	/* Same as above */
	sizeof(asn_DEF_PA_OTP_REQUEST_tags_1)
		/sizeof(asn_DEF_PA_OTP_REQUEST_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PA_OTP_REQUEST_1,
	14,	/* Elements count */
	&asn_SPC_PA_OTP_REQUEST_specs_1	/* Additional specs */
};

