/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "KerberosV5Spec2"
 * 	found in "modules/KerberosV5Spec2.asn1"
 */

#ifndef	_UInt32_H_
#define	_UInt32_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UInt32 */
typedef INTEGER_t	 UInt32_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UInt32;
asn_struct_free_f UInt32_free;
asn_struct_print_f UInt32_print;
asn_constr_check_f UInt32_constraint;
ber_type_decoder_f UInt32_decode_ber;
der_type_encoder_f UInt32_encode_der;
xer_type_decoder_f UInt32_decode_xer;
xer_type_encoder_f UInt32_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UInt32_H_ */
